removed support for 'skill' in manifest.nlu
Watson-Personal-Assistant/SkillBoilerplate pull request #27
Opened 2018-05-15 11:00 UTC by offerakrabi

removed checks for 'skill' as one of the nlu engines (added an error in case it's still there).
Tested manually seems to work fine.

git issue: https://github.ibm.com/ConsumerIoT/WA-dev-issues/issues/324

2018-05-15 11:16 UTC, erezbi commented
@offerakrabi you almost got me there. this should not be merged yet!
We first need to merge pre-release to master as part of the May release.

2018-05-15 13:08 UTC, troyibm reviewed
@offerakrabi I don't understand "manifest.nlu".  To the developer, wouldn't "manifest.json" be more correct?  I think the error in line 25 should end with "... in manifest.json".

2018-05-16 09:02 UTC, offerakrabi commented
updated error message

2018-06-04 13:21 UTC, erezbi approved these changes

2018-06-04 13:21 UTC, erezbi commented
@offerakrabi Code looks fine. What testing did you run on this?

2018-06-05 06:22 UTC, offerakrabi commented
@erezbi tested this manually. it's a problem testing the boilerplate because it requires nisha to update all the skill in the testing framework

2018-06-06 13:22 UTC, erezbi approved these changes

2018-06-06 13:25 UTC, erezbi commented
We need to test all of the relevant cases such as nlu value being:
only 'skill'.
empty.
Skill and some other nlu.
no skill and only other nlu.
We should automate these tests.

2018-06-06 17:17 UTC, troyibm commented
I think the manifest.json nlu property should have "skill" in it.  This is so skills will continue to work if the env variable is set for the Core to do NLU.  Once there is no possibility that the Core handles NLU, then "skill" should be removed from the nlu property in the boilerplate.  @erezbi @offerakrabi

2018-06-06 17:18 UTC, troyibm requested changes
I think the manifest.json nlu property should have "skill" in it. This is so skills will continue to work if the env variable is set for the Core to do NLU. Once there is no possibility that the Core handles NLU, then "skill" should be removed from the nlu property in the boilerplate

2018-06-07 07:03 UTC, offerakrabi commented
@troyibm 
Added 'skill' to manifest.
@erezbi 
I checked all these scenarios

2018-06-07 07:04 UTC, merged